language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
install:
  - pip install -e . --use-mirrors
  - make bootstrap-tests
script:
  - make test
notifications:
  irc:
    channels: "irc.freenode.org#sentry"
    on_success: change
    on_failure: change